In [5]:
 import pandas as pd

In [6]:
npr = pd.read_csv('npr.csv')

In [8]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [9]:
npr['Article'][0]


'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [10]:
len(npr)

11992

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer(max_df=0.9, min_df=2,stop_words='english')  # vacab ignore_high_freq words(0-1)  # min_document(the number of documents the word should be) feeq

transform each term

In [14]:
dtm = cv.fit_transform(npr['Article']) # document_term_matrix

In [15]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.longlong'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [19]:
from sklearn.decomposition import LatentDirichletAllocation

In [22]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

###### DEpends on domain

n_components HIGHER more specific -> subdomain info

## TRain -> large time as iterative

In [23]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=7, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=42, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

 ### Grab the vocabulary of words


In [25]:
len(cv.get_feature_names())

54777

In [26]:
type(cv.get_feature_names())

list

In [31]:
cv.get_feature_names()[10303]

'commandeer'

In [34]:
import random
random_word_id =random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'capps'

  ### Grab the topics


In [36]:
len(LDA.components_)

7

In [38]:
LDA.components_.shape

(7, 54777)

In [39]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [40]:
single_topic = LDA.components_[0]

In [41]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

##### Index Sort -> argsort

In [45]:
import numpy as np 
arr = np.array([10,200,1])
arr
arr.argsort() 

array([2, 0, 1])

In [46]:
# ARGSORT-> INDEX POSITIONS SORTED FROM LEAST-> GREATEST
# TOP 10 VALUES (10 GREATEST VALUES)
#LAST 10 VALUES of ARGSORT()
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [48]:
top_10_words=single_topic.argsort()[-10:]

In [49]:
for index in top_10_words:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


  # Grab the highest probability words per topic

In [52]:
for i,topic in enumerate(LDA.components_):
    print (f"THE TOP 15 WORDS FOR TOPIC {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print ('\n')
    print ('\n')

THE TOP 15 WORDS FOR TOPIC 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'thi

In [53]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.longlong'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [55]:
topic_results = LDA.transform(dtm) # fit transform

In [56]:
topic_results.shape

(11992, 7)

In [57]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [60]:
topic_results[9].argmax()

2

In [61]:
npr['Topic']= topic_results.argmax(axis=1)

In [62]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
5      I did not want to join yoga class. I hated tho...      3
6      With a   who has publicly supported the debunk...      3
7      I was standing by the airport exit, debating w...      2
8      If movies were trying to be more realistic, pe...      3
9      Eighteen years ago, on New Year’s Eve, David F...      2
10     For years now, some of the best, wildest, most...      5
11     For years now, some of the best, wildest, most...      5
12     The Colorado River is like a giant bank accoun...      2
13     For the last installment of NPR’s holiday reci...      2
14     Being overweight can raise your blood pressure...      3
15     Who’s the YouTube star of 2016? Adele singing ...      5
16     Here’s a quick roundup of some of the   you ma...      2
17     Ben Johnston doesn’t follow the rules of music...      5
18     David Bowie, Prince and George Michael are all...      5
19     In November, the typically straitlaced Office ...      1
20     This is the time of year when everybody is mak...      5
21     Terrorist attacks, hurricanes, a divisive U. S...      6
22     We all experience stress at work, no matter th...      6
23     When John Fahey recorded The New Possibility i...      5
24     This year was one of   hacks, exploding smartp...      6
25     From West Virginia to Wyoming, coal country ov...      4
26     Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      1
27     On the morning of Jan. 1, Los Angeles resident...      1
28     In September, reproductive endocrinologist Joh...      3
29     In an effort to take advantage of the intimate...      3
...                                                  ...    ...
11962  Updated at 6:15 p. m. The White House has anno...      1
11963  The actress Debbie Reynolds’ death just one da...      3
11964  Here’s a timely reminder for all you   reveler...      6
11965  Every year in late November, the New Mexican v...      2
11966  Time to get together the transcripts and the t...      6
11967  Hollywood is in the process of closing out a  ...      5
11968  Dealing with a flood of   pardon requests amou...      1
11969  Rashaan Salaam, the former college football st...      3
11970  On the top of Hawaii’s Mauna Kea mountain Thur...      6
11971  A tiny pink peanut is not a white rhinoceros. ...      2
11972  In a disappointment to Alzheimer’s patients an...      3
11973  In my early 20s, smitten by the mythic underpi...      5
11974  It’s been a lively year for social media maven...      1
11975  This is not a review. It started out as one: I...      5
11976  On a summer’s day in December, a warehouse in ...      2
11977  Elections aren’t exactly cozy, even in the bes...      5
11978  Although her oldest child, Ben, is 10 years ol...      3
11979  When a political scandal explodes in France, t...      1
11980  The darkest moment for American police this ye...      4
11981  Russia was ordered to vacate two compounds it ...      2
11982  A North Carolina judge is temporarily blocking...      4
11983  China’s police are under fire this week as cit...      1
11984  Before the virus overwhelmed Puerto Rico, Zika...      3
11985  It seems everything today has a flavor wheel, ...      2
11986  In the final days of a year that has become kn...      2
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]